### PR TITLE
Fix the width of the input field

### PR DESCRIPTION
**Pull request by gmclelland**
Here is a PR to fix the width of input field as noted in issue #2. 

I'm using this technique https://boulderinformationservices.wordpress.com/2011/02/02/input-field-and-submit-button-on-the-same-line-full-width/ to keep the button and the input on the same line.

Hope that helps

### CODE REVIEW

**Comment by marcostoll** [comment]
Hi gmclelland and thank you for your assistance!

Frontend stuff is surely not my primary domain ... ;-}

**Comment by gmclelland** [comment]
Glad I could help.  This is a very helpful module for content editors.  I received some help as well from Robin S at https://processwire.com/talk/topic/14462-add-div-around-an-input-field/ 

I never could figure out how to wrap just the input(and not the button) with a div using appendMarkup and prependMarkup.  Oh well, I just hope it isn't a bug in Processwire.

**Comment by matjazpotocnik** [comment]
@marcostoll: thanks for the module and for the change in css proposed by @gmclelland  and Robin S. Would you mind updating the version from 100 to 101?

**Comment by gmclelland** [comment]
Hold up.  The extra markup I added fixed the styling, but might have broken the js functionality.  After clicking the "Choose Url" button, nothing gets returned to the input.

**Comment by gmclelland** [comment]
Fix is coming soon.  I'll make another pull request.

**Comment by gmclelland** [comment]
Here is the new pull request https://github.com/marcostoll/processwire-fieldtype-assisted-url/pull/4 in case anybody wants to try it out.

**Pull request merged**
